# Este é um fluxo de trabalho básico utilizado na Aula sobre GitHub Actios DevOps Básico.

#nome do meu fluxo
name: CI test

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para a ramificação "principal"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite que você execute este fluxo de trabalho manualmente a partir da guia "Actions"
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta de um ou mais trabalhos que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  build:
    # Informando onde o trabalho será executado
    runs-on: ubuntu-latest

    # Steps representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
      # Check-out do seu repositório em $GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo
      - uses: actions/checkout@v3

      # Executa um único comando usando o shell runners
      - name: executando docker 
        run: docker run docker/whalesay cowsay DEVOPS IT TALENT

      # Executa um conjunto de comandos usando o shell runners
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
